import { z } from "zod";

/**
 * Schema for validating Q&A generation responses from AI
 */
export const GeneratedQASchema = z.object({
  questions: z.array(
    z.object({
      question: z.string(),
      options: z.object({
        A: z.string(),
        B: z.string(),
        C: z.string(),
        D: z.string(),
      }),
      correct_option: z.enum(["A", "B", "C", "D"]),
    })
  ),
});

/**
 * Type for a single Q&A item generated by AI
 */
export interface GeneratedQA {
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  correct_option: "A" | "B" | "C" | "D";
}
