import { z } from "zod";

/**
 * Schema for validating Q&A generation responses from AI
 */
export const GeneratedQASchema = z
  .array(
    z.object({
      question: z.string().min(1, "Question cannot be empty"),
      options: z.object({
        A: z.string().min(1, "Option A cannot be empty"),
        B: z.string().min(1, "Option B cannot be empty"),
        C: z.string().min(1, "Option C cannot be empty"),
        D: z.string().min(1, "Option D cannot be empty"),
      }),
      correct_option: z.enum(["A", "B", "C", "D"]),
    })
  )
  .min(3, "At least 3 questions must be generated");

/**
 * Type for a single Q&A item generated by AI
 */
export interface GeneratedQA {
  question: string;
  options: {
    A: string;
    B: string;
    C: string;
    D: string;
  };
  correct_option: "A" | "B" | "C" | "D";
}
